services:

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    command: alembic upgrade head

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
      - alembic
    env_file:
     .env

  db:
    image: postgres
    volumes:
      - ../postgres_data:/var/lib/postgresql/data
    env_file:
     .env
    # ports:
    #   - '5433:5432'
