"""new assoc logiccs

Revision ID: 14c24f2d30f3
Revises: fbb293efca35
Create Date: 2025-01-23 16:13:08.504453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14c24f2d30f3'
down_revision: Union[str, None] = 'fbb293efca35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_category_association',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('object_category_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_category_association',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='object_category_association_category_id_fkey'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], name='object_category_association_object_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='object_category_association_pkey')
    )
    op.drop_table('product_category_association')
    # ### end Alembic commands ###
