"""add project_id to object

Revision ID: 27355f6fe513
Revises: 19200e4dbaae
Create Date: 2025-03-24 14:45:53.175433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27355f6fe513'
down_revision: Union[str, None] = '19200e4dbaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'objects', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'objects', type_='foreignkey')
    op.drop_column('objects', 'project_id')
    # ### end Alembic commands ###
