"""deprecate unique to category names

Revision ID: 34aaef28ef1f
Revises: ab5cdd9fbb0c
Create Date: 2025-03-22 13:29:02.688517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34aaef28ef1f'
down_revision: Union[str, None] = 'ab5cdd9fbb0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    # ### end Alembic commands ###
