"""turn file_storage to array

Revision ID: 80bc667e3e7d
Revises: aa16a74f41e6
Create Date: 2025-02-19 16:21:15.807340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects.postgresql import ARRAY


# revision identifiers, used by Alembic.
revision: str = '80bc667e3e7d'
down_revision: Union[str, None] = 'aa16a74f41e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Преобразует столбец file_storage из строки в массив строк (VARCHAR[]).
    Если в file_storage есть обычные строки, они оборачиваются в массив.
    """

    # 1. Преобразуем строки в корректные массивы (если файл одно значение, делаем массив из одного элемента)
    op.execute(
        "UPDATE objects SET file_storage = ARRAY[file_storage] WHERE file_storage IS NOT NULL AND NOT file_storage LIKE '{%'"
    )

    # 2. Меняем тип столбца с VARCHAR на VARCHAR[]
    op.alter_column(
        "objects",
        "file_storage",
        existing_type=sa.VARCHAR(),
        type_=sa.ARRAY(sa.VARCHAR()),
        existing_nullable=True,
        postgresql_using="file_storage::TEXT[]"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
