"""turn file_storage to array

Revision ID: 80bc667e3e7d
Revises: aa16a74f41e6
Create Date: 2025-02-19 16:21:15.807340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects.postgresql import ARRAY


# revision identifiers, used by Alembic.
revision: str = '80bc667e3e7d'
down_revision: Union[str, None] = 'aa16a74f41e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Преобразуем текущие строки в массивы строк (например, 'string' -> '{"string"}')
    op.execute("""
        UPDATE objects
        SET file_storage = CONCAT('{"', file_storage, '"}')
        WHERE links IS NOT NULL;
    """)

    # Изменяем тип колонки на ARRAY с использованием postgresql_using
    op.alter_column(
        'objects',
        'file_storage',
        type_=ARRAY(sa.String),
        nullable=True,
        postgresql_using="file_storage::TEXT[]"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
