"""add branches

Revision ID: 9c7dc2510209
Revises: be2952d71235
Create Date: 2025-02-01 20:45:01.946937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7dc2510209'
down_revision: Union[str, None] = 'be2952d71235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.drop_constraint('objects_parent_object_id_fkey', 'objects', type_='foreignkey')
    op.create_foreign_key(None, 'objects', 'objects', ['parent_id'], ['id'])
    op.drop_column('objects', 'parent_object_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('parent_object_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'objects', type_='foreignkey')
    op.create_foreign_key('objects_parent_object_id_fkey', 'objects', 'objects', ['parent_object_id'], ['id'])
    op.drop_column('objects', 'parent_id')
    # ### end Alembic commands ###
