"""links to array

Revision ID: aa16a74f41e6
Revises: 9c7dc2510209
Create Date: 2025-02-05 15:31:06.333010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects.postgresql import ARRAY

# revision identifiers, used by Alembic.
revision: str = 'aa16a74f41e6'
down_revision: Union[str, None] = '9c7dc2510209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # Преобразуем текущие строки в массивы строк (например, 'string' -> '{"string"}')
    op.execute("""
        UPDATE objects
        SET links = CONCAT('{"', links, '"}')
        WHERE links IS NOT NULL AND links NOT LIKE '{%';
    """)

    # Изменяем тип колонки на ARRAY с использованием postgresql_using
    op.alter_column(
        'objects',
        'links',
        type_=ARRAY(sa.String),
        nullable=True,
        postgresql_using="links::TEXT[]"
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
