"""add branches

Revision ID: be2952d71235
Revises: 80570b16e64c
Create Date: 2025-02-01 20:25:36.310101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2952d71235'
down_revision: Union[str, None] = '80570b16e64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('parent_object_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'objects', 'objects', ['parent_object_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'objects', type_='foreignkey')
    op.drop_column('objects', 'parent_object_id')
    # ### end Alembic commands ###
