"""turn image and icon to bool

Revision ID: d9cbee19b563
Revises: 80bc667e3e7d
Create Date: 2025-02-19 16:33:54.313868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9cbee19b563'
down_revision: Union[str, None] = '80bc667e3e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """
    Преобразует столбцы icon и image из строкового (VARCHAR) типа в булевый (BOOLEAN).
    Если значение не NULL, оно становится TRUE, иначе FALSE.
    """
    # 1. Обновляем существующие данные перед сменой типа
    op.execute(
        "UPDATE objects SET icon = 'true' WHERE icon IS NOT NULL"
    )
    op.execute(
        "UPDATE objects SET icon = 'false' WHERE icon IS NULL"
    )
    op.execute(
        "UPDATE objects SET image = 'true' WHERE image IS NOT NULL"
    )
    op.execute(
        "UPDATE objects SET image = 'false' WHERE image IS NULL"
    )

    # 2. Меняем тип столбцов с VARCHAR на BOOLEAN
    op.alter_column('objects', 'icon',
        existing_type=sa.VARCHAR(),
        type_=sa.Boolean(),
        existing_nullable=True,
        postgresql_using="icon::boolean"
    )

    op.alter_column('objects', 'image',
        existing_type=sa.VARCHAR(),
        type_=sa.Boolean(),
        existing_nullable=True,
        postgresql_using="image::boolean"
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('objects', 'image',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('objects', 'icon',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
